apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default  # Change to your namespace

resources:
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  # - ingress.yaml  # Uncomment if you want to expose externally

# Common labels
commonLabels:
  app: ippool
  managed-by: kustomize

# Images
images:
  - name: ippool
    newName: your-registry/ippool  # Change to your container registry
    newTag: latest
